services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: development
    packages:
      apt:
        - portaudio19-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-dev
